[package]
name = "webgpu-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.19"
winit = "0.29"

env_logger = "0.11"
log = "0.4"
pollster = "0.3"
async-trait = "0.1"
